import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/common/AppHeader";
import AppFooter from "@/components/common/AppFooter";
import ProviderWrapper from "@/components/common/ProviderWrapper";
import FloatingActionButton from "@/components/common/FloatingActionButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {default:"기아 비즈(Kia Biz) - 친환경 모빌리티 서비스", template:'%s | 기아 비즈(Kia Biz) - 친환경 모빌리티 서비스'},
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProviderWrapper>
          <AppHeader />
          {children}
          <FloatingActionButton/>
          <AppFooter />
        </ProviderWrapper>
      </body>
    </html>
  );
}
